import {
  Activity,
  AlertTriangle,
  Bell,
  Camera,
  Check,
  CheckCircle,
  ChevronRight,
  ChevronLeft,
  Clock,
  Cross,
  Edit3,
  Eye,
  EyeOff,
  Fingerprint,
  Home,
  Info,
  Languages,
  Link,
  Lock,
  LogOut,
  MapPin,
  Map,
  Menu,
  Mic,
  Minus,
  Navigation,
  Phone,
  Plus,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Siren,
  Smartphone,
  Star,
  Trash2,
  User,
  UserPlus,
  UserMinus,
  Users,
  Volume2,
  Wifi,
  WifiOff,
  X,
  XCircle,
  Zap,
  Battery,
  BatteryLow,
  Heart,
  Droplet,
  Ruler,
  Weight,
  Calendar,
  Moon,
  Sun,
  Download,
  Trash,
  ChevronUp,
  ChevronDown,
  Footprints,
  Send,
} from 'lucide-react-native';

const iconMap = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  bell: Bell,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  clock: Clock,
  cross: Cross,
  edit: Edit3,
  eye: Eye,
  'eye-off': EyeOff,
  fingerprint: Fingerprint,
  home: Home,
  info: Info,
  languages: Languages,
  link: Link,
  lock: Lock,
  logout: LogOut,
  'map-pin': MapPin,
  map: Map,
  menu: Menu,
  mic: Mic,
  minus: Minus,
  navigation: Navigation,
  phone: Phone,
  plus: Plus,
  search: Search,
  settings: Settings,
  share: Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  siren: Siren,
  smartphone: Smartphone,
  star: Star,
  trash: Trash,
  'trash-2': Trash2,
  user: User,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  users: Users,
  volume: Volume2,
  wifi: Wifi,
  'wifi-off': WifiOff,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
  battery: Battery,
  'battery-low': BatteryLow,
  heart: Heart,
  droplet: Droplet,
  ruler: Ruler,
  weight: Weight,
  calendar: Calendar,
  moon: Moon,
  sun: Sun,
  download: Download,
  footprints: Footprints,
  send: Send,
};

export type IconName = keyof typeof iconMap;

export function Icon({
  name,
  size = 24,
  color,
  strokeWidth = 2,
}: {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const Component = iconMap[name];
  if (!Component) return null;
  return <Component size={size} color={color} strokeWidth={strokeWidth} />;
}

export function getIconComponent(name: string) {
  return iconMap[name as IconName];
}
